### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adomo** [colmdoyle/pobal#42]
Hi Colm, I'm looking into doing an app similar to 5calls but for Ireland and the data you have would be perfect for my initial setup.

Can you provide some additional documentation to explain how to set up my own instance?

**Comment by colmdoyle** [comment]
The software itself doesn't automatically collect data. It's all manually entered.

Setup is essentially just deployed to a box running Ruby, but we could definitely document it better.

**Comment by colmdoyle** [comment]
Fivecalls-esque functionality is definitely something we would build into pobal though, if we could get the data on who to contact on what issue.

**Comment by adomo** [comment]
> The software itself doesn't automatically collect data. It's all manually entered.

Ah, I misunderstood the functionality, I've had issues in the past trying to match addresses to constituencies/local areas so I thought this would be ideal.

**Comment by colmdoyle** [comment]
Ah, ok. That's MapIt by MySociety you need so.

https://github.com/mysociety/mapit
