### ISSUE TITLE
DNW / DC boundaries 2020

### ISSUE THREAD

**Issue by eoinomahony** [colmdoyle/pobal#60]
Dublin NW and Dublin Central swapped a number of EDs for the 2019 GE. Can the boundaries be changed so that this error  - attached - can be rectified? <https://mega.nz/file/BS4kmDzD#6wSP-VL-Guw8rPaYMnsProxshxxkuQHmZQLQQEfjb6g>

**Comment by gp-dublincentral** [comment]
@colmdoyle - if we were to submit a pull request for this issue is it something you'd take a look at?

Or is it really something that needs to be updated in the MapIt instance?  In which case would you like some help doing that?

Paschal.

**Comment by gp-dublincentral** [comment]
OK understood, I think we all have one of those lists ;-)

Here's the map we did ourselves for Dublin Central, I can point you to the authoritative source data for that if required.
http://umap.openstreetmap.fr/en/map/dublin-central-electoral-district-map_356159#14/53.3718/-6.2611

Or any other way we can help, just shout.
